services:
  db:
    image: postgres:17
    container_name: nusaloka_db
    restart: unless-stopped
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - nusaloka-net

  redis:
    image: redis:7
    container_name: nusaloka_redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
    networks:
      - nusaloka-net

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - mailpit_data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: true
      MP_SMTP_AUTH_ALLOW_INSECURE: true
    networks:
      - nusaloka-net

  gateway:
    build: 
      context: .
      dockerfile: ./docker/gateway/Dockerfile
    container_name: api_gateway
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    env_file:
      - .env
    networks:
      - nusaloka-net

  account-service:
    build: 
      context: .
      dockerfile: ./docker/account/Dockerfile
    container_name: account_service
    ports:
      - ${ACCOUNT_SERVICE_PORT}:${ACCOUNT_SERVICE_PORT}
    env_file:
      - .env
    networks:
      - nusaloka-net

  trip-service:
    build: 
      context: .
      dockerfile: ./docker/trip/Dockerfile
    container_name: trip_service
    ports:
      - ${TRIP_SERVICE_PORT}:${TRIP_SERVICE_PORT}
    env_file:
      - .env
    networks:
      - nusaloka-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - nusaloka-net

volumes:
  pg_data:
  redis_data:
  mailpit_data:


networks:
  nusaloka-net:
    driver: bridge
