blank_issues_enabled: false
contact_links:
  - name: Tanya-tanya atau diskusi santai 💬
    url: https://github.com/evelinix/nusaloka/discussions
    about: Kalau bingung atau cuma mau ngobrol soal ide, bisa langsung ke forum diskusi yaa~
